#!/bin/sh
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.5
export GTK_PATH=:/usr/lib/gtk-2.0
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORMTHEME=qt5ct
export _JAVA_AWT_WM_NONREPARENTING=1

export PATH=~/.dwm/scripts:$PATH
